#!/bin/sh
LOCK=/home/vixima/.config/eww/temp/redshift.lock
eww=/home/vixima/.local/bin/eww

if [ -f "$LOCK" ]; then
    rm -rf "$LOCK"
    $eww update redshiftToggled=""
    pkill -USR1 '^redshift$'
else 
    touch "$LOCK"
    $eww update redshiftToggled="pinkBG"
    if pgrep -x "redshift" > /dev/null 
    then
        pkill -USR1 '^redshift$'
    else
        redshift -l 52.366291:-0.675810
    fi
fi
