#!/bin/sh
LOCK=/home/vixima/.config/eww/temp/bar.lock
eww=/home/vixima/.local/bin/eww

if [ -f "$LOCK" ]; then
    rm -rf "$LOCK"
    bspc config left_padding 46
    $eww open bar
else 
    touch "$LOCK"
    bspc config left_padding 0
    $eww close bar
fi
