#!/bin/sh
LOCK=/home/vixima/.config/eww/temp/cc.lock
eww=/home/vixima/.local/bin/eww

if [ -f "$LOCK" ]; then
    rm -rf "$LOCK"
    $eww close controlcentre
else 
    touch "$LOCK"
    if [ $GDMSESSION = "hyprland" ]; then
        $eww open controlcentre --arg wm=hyprland
    else
        $eww open controlcentre --arg wm=bspwm
    fi
fi
