#!/bin/sh
LOCK=/home/vixima/.config/eww/temp/transparency.lock
CONFDIR=/home/vixima/.config

css() { 
    if [[ "$1" == "-off" ]]; then
        sed -i '' -e '1,3s/0\.9/1\.0/;1,3s/0\.8/1\.0/;1,3s/0\.7/1\.0/;' $CONFDIR/eww/colours/camelliahopeDark.scss
        sed -i '' -e '1,3s/0\.9/1\.0/;1,3s/0\.8/1\.0/;1,3s/0\.7/1\.0/;' $CONFDIR/eww/colours/camelliahopeLight.scss
    elif [[ "$1" == "-on" ]]; then
        sed -i '' -e '1s/1.0/0.9/;2s/1.0/0.8/;3s/1.0/0.7/;' $CONFDIR/eww/colours/camelliahopeDark.scss
        sed -i '' -e '1s/1\.0/0\.9/;2s/1\.0/0\.8/;3s/1\.0/0\.7/;' $CONFDIR/eww/colours/camelliahopeLight.scss
    fi
}

term() { 
    if [[ "$1" == "-off" ]]; then
        sed -i '' -e '27s/0\.9/1\.0/;' $CONFDIR/wezterm/wezterm.lua
    elif [[ "$1" == "-on" ]]; then
        sed -i '' -e '27s/1\.0/0\.9/;' $CONFDIR/wezterm/wezterm.lua
    fi
}

rofi() { 
    if [[ "$1" == "-off" ]]; then
        sed -i '' -e '2,4s/0\.9/1\.0/;2,4s/0\.8/1\.0/;2,4s/0\.7/1\.0/;' $CONFDIR/rofi/camelliahopeDark.rasi
        sed -i '' -e '2,4s/0\.9/1\.0/;2,4s/0\.8/1\.0/;2,4s/0\.7/1\.0/;' $CONFDIR/rofi/camelliahopeLight.rasi
    elif [[ "$1" == "-on" ]]; then
        sed -i '' -e '2s/1\.0/0\.9/;3s/1\.0/0\.8/;4s/1\.0/0\.7/;' $CONFDIR/rofi/camelliahopeDark.rasi
        sed -i '' -e '2s/1\.0/0\.9/;3s/1\.0/0\.8/;4s/1\.0/0\.7/;' $CONFDIR/rofi/camelliahopeLight.rasi
    fi
}

if  [[ -f "$LOCK" ]]; then
    rm -rf "$LOCK"
    css -on
    term -on
    rofi -on
else
    touch "$LOCK"
    css -off
    term -off
    rofi -off
fi
