#! /bin/sh
eww=/home/vixima/.local/bin/eww

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config left_padding 46

bspc config border_radius 16

bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc config focused_border_color \#FA3867
bspc config normal_border_color \#333438
bspc config border_width 0

setxkbmap gb

compfy &

dunst &
dunstctl rule dnd disable &

rofi-polkit-agent &

#xrandr --auto && xrandr --output HDMI-A-1 --off

$eww kill
$eww daemon
$eww open bar

nitrogen --restore

sh /home/vixima/.config/eww/scripts/soundLogin
#x0vncserver -display :0 -rfbauth /home/npe/.vnc/passwd

mpd &
yams &

gsettings set org.gnome.desktop.interface cursor-theme Bibata-CamelliaHopeDark
xsetroot -cursor_name left_ptr

xinput --set-prop 11 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 11 'libinput Tapping Enabled' 1
